Fix issue caused by upgrading to Electron 15..
Electron Version 15.2 caused error:
"window.require is not a function"
Adding contextIsolation: false in webPreferences fixes issue.